name: APK-fmTV Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clone Project
        run: git clone -b dev https://github.com/FongMi/TV.git
  



      - name: Setup Gradle

        uses: gradle/gradle-build-action@v3







      - name: Run build with Gradle
        
        run: |
    

          cd TV
          chmod +x gradlew
          ./gradlew assemblemobileJavarelease build --scan
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*
